# Generated by Django 5.0.6 on 2024-06-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SeasonalEvents",
            new_name="SeasonalEvent",
        ),
    ]
