# Generated by Django 5.0.6 on 2024-06-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rename_seasonalevents_seasonalevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
