# Generated by Django 5.0.6 on 2024-06-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_attribute_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productline",
            name="attribute_values",
            field=models.ManyToManyField(
                related_name="attribute_values", to="inventory.attributevalue"
            ),
        ),
    ]
