# Generated by Django 4.0.4 on 2024-07-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
